steps:
#install
- name: 'gcr.io/cloud-builders/npm'
  args: ['install']

- name: 'gcr.io/cloud-builders/nvm'
  args: ['install 12.14.0']

  #test
- name: 'gcr.io/cloud-builders/npm'
  args: ['run', 'test']

  #build
- name: 'gcr.io/cloud-builders/npm'
  args: ['run', 'build']

  #deploy
- name: 'gcr.io/$PROJECT_ID/firebase'
  args: ['deploy']